INSERT INTO AUTHOR(ID, FIRST_NAME, LAST_NAME) VALUES(1, 'Mac', 'Java');
INSERT INTO AUTHOR(ID, FIRST_NAME, LAST_NAME) VALUES(2, 'John', 'Doe');
INSERT INTO AUTHOR(ID, FIRST_NAME, LAST_NAME) VALUES(3, 'Jane', 'Due');

INSERT INTO BOOK(ID, TITLE, PRICE, AUTHOR_ID) VALUES(1, 'Java for Beginner', 100.00, 1);
INSERT INTO BOOK(ID, TITLE, PRICE, AUTHOR_ID) VALUES(2, 'Python for Beginner', 80.00, 1);
INSERT INTO BOOK(ID, TITLE, PRICE, AUTHOR_ID) VALUES(3, 'Ruby for Beginner', 85.00, 3);
INSERT INTO BOOK(ID, TITLE, PRICE, AUTHOR_ID) VALUES(4, 'Intro to Computer Science', 50.00, 2);
INSERT INTO BOOK(ID, TITLE, PRICE, AUTHOR_ID) VALUES(5, 'Design Pattern', 150.00, 3);
